name: 'heap'
version: '1.0'

profile: 'default'

source-paths: ["models"]   # paths with source code to compile
analysis-paths: ["analysis"] # path with analysis files which are compiled, but not run
target-path: "target"      # path for compiled code
clean-targets: ["target, dbt_modules"]  # directories removed by the clean task
test-paths: ["test"]       # where to store test results
data-paths: ["data"]       # load CSVs from this directory with `dbt seed`

require-dbt-version: ">=0.15.0"

models:
  heap:
    vars:
      users_table:      #schema.table
      sessions_table:   #schema.table
      events_table:     #schema.table
